import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Navigation from "../components/Navigation";

const Home: NextPage = () => {
  // const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  const {data: session} = useSession();

  if (session) {
    return (
      <div>
        <Head>
          <title>Home</title>
        </Head>
        <Navigation />
        <div className="flex flex-col items-center justify-center h-screen">
        <div className="bg-white rounded-lg shadow-lg p-8 flex flex-col items-center">
          <h1 className="text-center text-2xl font-bold mb-4">
            Hello {session.user?.name}
          </h1>
        </div>
      </div>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <div className="flex flex-col items-center justify-center h-screen">
        <div className="bg-white rounded-lg shadow-lg p-8 flex flex-col items-center">
          <h1 className="text-center text-2xl font-bold mb-4">
            Create T3 App
          </h1>
          <p>Welcome to my blog</p>
        </div>
      </div>
    </>
  );
};

export default Home;
