import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  // const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  const {data: session} = useSession();

  if (session) {
    return (
      <div>
        <Head>
          <title>Home</title>
        </Head>

            <div className="flex flex-col items-center justify-center h-screen">
        <div className="bg-white rounded-lg shadow-lg p-8 flex flex-col items-center">
          <h1 className="text-center text-2xl font-bold mb-4">
            Hello {session.user?.name}
          </h1>
          <button onClick={() => signOut()} className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            Log Out
          </button>
        </div>
      </div>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Using tailwindcss, create a white card in the middle of the page */}
      <div className="flex flex-col items-center justify-center h-screen">
        <div className="bg-white rounded-lg shadow-lg p-8 flex flex-col items-center">
          <h1 className="text-center text-2xl font-bold mb-4">
            Create T3 App
          </h1>
          <button onClick={() => signIn()} className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            Log in
          </button>
        </div>
      </div>
    </>
  );
};

export default Home;
